/* ====== 凡人修仙传MUD · 扩展4数据（主线推进/宗门排名/支线/强迫双修/副本） ====== */

// ===== 宗门/家族排名系统 =====
// rank越低排名越高(1=最强)，strength为整体实力评分
const SECT_RANKINGS = {
  "immortal_palace":   {rank:1,  name:"仙宫",     overallStrength:100, masterCultLevel:25, elderCultLevel:23, grandElderCultLevel:24},
  "spirit_world_sect": {rank:2,  name:"灵界天宗", overallStrength:85,  masterCultLevel:20, elderCultLevel:18, grandElderCultLevel:21},
  "star_palace":       {rank:3,  name:"星宫",     overallStrength:75,  masterCultLevel:16, elderCultLevel:14, grandElderCultLevel:17},
  "yun_family":        {rank:4,  name:"云家",     overallStrength:65,  masterCultLevel:15, elderCultLevel:13, grandElderCultLevel:16},
  "demon_valley":      {rank:5,  name:"魔道宗",   overallStrength:62,  masterCultLevel:14, elderCultLevel:12, grandElderCultLevel:15},
  "blood_flame":       {rank:6,  name:"血焰教",   overallStrength:58,  masterCultLevel:13, elderCultLevel:11, grandElderCultLevel:14},
  "ghost_spirit":      {rank:7,  name:"鬼灵门",   overallStrength:55,  masterCultLevel:12, elderCultLevel:10, grandElderCultLevel:13},
  "yellow_maple":      {rank:8,  name:"黄枫谷",   overallStrength:50,  masterCultLevel:11, elderCultLevel:9,  grandElderCultLevel:12},
  "purple_cloud":      {rank:9,  name:"紫云宫",   overallStrength:48,  masterCultLevel:11, elderCultLevel:9,  grandElderCultLevel:12},
  "yao_family":        {rank:10, name:"姚家",     overallStrength:45,  masterCultLevel:10, elderCultLevel:8,  grandElderCultLevel:11},
  "mu_family":         {rank:11, name:"慕容家",   overallStrength:42,  masterCultLevel:10, elderCultLevel:8,  grandElderCultLevel:11},
  "blue_water":        {rank:12, name:"碧水宗",   overallStrength:40,  masterCultLevel:10, elderCultLevel:8,  grandElderCultLevel:11},
  "clear_sound":       {rank:13, name:"清音门",   overallStrength:38,  masterCultLevel:10, elderCultLevel:8,  grandElderCultLevel:11},
  "spirit_beast":      {rank:14, name:"灵兽山",   overallStrength:36,  masterCultLevel:10, elderCultLevel:8,  grandElderCultLevel:11},
  "thunder_mountain":  {rank:15, name:"雷山派",   overallStrength:34,  masterCultLevel:10, elderCultLevel:8,  grandElderCultLevel:11},
  "iron_sword":        {rank:16, name:"铁剑门",   overallStrength:32,  masterCultLevel:10, elderCultLevel:8,  grandElderCultLevel:11},
  "zhao_family":       {rank:17, name:"赵家",     overallStrength:30,  masterCultLevel:9,  elderCultLevel:7,  grandElderCultLevel:10},
  "wang_family":       {rank:18, name:"王家",     overallStrength:25,  masterCultLevel:8,  elderCultLevel:6,  grandElderCultLevel:9},
  "li_family":         {rank:19, name:"李家",     overallStrength:22,  masterCultLevel:8,  elderCultLevel:6,  grandElderCultLevel:9},
  "han_family":        {rank:20, name:"韩家",     overallStrength:18,  masterCultLevel:7,  elderCultLevel:5,  grandElderCultLevel:8},
  "seven_profound":    {rank:21, name:"七玄门",   overallStrength:15,  masterCultLevel:7,  elderCultLevel:5,  grandElderCultLevel:8},
  "qin_family":        {rank:22, name:"秦家",     overallStrength:12,  masterCultLevel:6,  elderCultLevel:4,  grandElderCultLevel:7},
};

// ===== 宗门/家族在地图上的位置（扩展WORLD_MAP用） =====
const SECT_MAP_LOCATIONS = {
  "seven_profound":   {mapKey:"七玄门集镇",  subArea:"七玄门主殿"},
  "yellow_maple":     {mapKey:"黄枫谷",      subArea:"黄枫谷主殿"},
  "blue_water":       {mapKey:"天南坊市城",  subArea:"碧水宗驻地"},
  "clear_sound":      {mapKey:"天南坊市城",  subArea:"清音门驻地"},
  "purple_cloud":     {mapKey:"天南坊市城",  subArea:"紫云宫驻地"},
  "iron_sword":       {mapKey:"天南坊市城",  subArea:"铁剑门山门"},
  "spirit_beast":     {mapKey:"天南坊市城",  subArea:"灵兽山"},
  "thunder_mountain": {mapKey:"天南坊市城",  subArea:"雷山派山门"},
  "ghost_spirit":     {mapKey:"天南坊市城",  subArea:"鬼灵门驻地"},
  "blood_flame":      {mapKey:"天南坊市城",  subArea:"血焰教驻地"},
  "star_palace":      {mapKey:"乱星海",      subArea:"星宫主殿"},
  "demon_valley":     {mapKey:"坠魔谷",      subArea:"魔道宗山门"},
  "spirit_world_sect":{mapKey:"灵界",        subArea:"天宗山门"},
  "immortal_palace":  {mapKey:"仙界",        subArea:"仙宫"},
  "han_family":       {mapKey:"天南坊市城",  subArea:"韩家宅邸"},
  "wang_family":      {mapKey:"天南坊市城",  subArea:"王家宅邸"},
  "mu_family":        {mapKey:"天南坊市城",  subArea:"慕容家宅邸"},
  "li_family":        {mapKey:"乱星海渡口",  subArea:"李家宅邸"},
  "yun_family":       {mapKey:"灵界",        subArea:"云家仙府"},
  "yao_family":       {mapKey:"灵界",        subArea:"姚家丹堂"},
  "zhao_family":      {mapKey:"慕兰草原",    subArea:"赵家营地"},
  "qin_family":       {mapKey:"天南坊市城",  subArea:"秦家符铺"},
};

// ===== 宗门副本/洞天定义 =====
const SECT_DUNGEONS = {
  "seven_profound":   {name:"七玄门后山秘境",   desc:"七玄门后山隐藏的小型秘境，有低阶妖兽出没。", reqStage:0,  enemyLv:0,  rewards:["healing_pill","qi_pill","spirit_grass","iron_sword"]},
  "yellow_maple":     {name:"黄枫谷灵木林秘境", desc:"黄枫谷深处的灵木林，古木参天，灵气浓郁。", reqStage:0,  enemyLv:1,  rewards:["foundation_pill","qingshuang_sword","blue_robe","spirit_gather_ring"]},
  "blue_water":       {name:"碧水宗水府秘境",   desc:"碧水宗水底秘境，水灵充沛。", reqStage:0,  enemyLv:1,  rewards:["foundation_pill","qingshuang_sword","blue_robe"]},
  "clear_sound":      {name:"清音门音谷秘境",   desc:"清音门音谷，音波缭绕。", reqStage:0,  enemyLv:1,  rewards:["foundation_pill","blue_robe","spirit_gather_ring"]},
  "purple_cloud":     {name:"紫云宫云海秘境",   desc:"紫云宫云海秘境，紫气弥漫。", reqStage:0,  enemyLv:2,  rewards:["core_formation_pill","zisha_sword","purple_armor"]},
  "iron_sword":       {name:"铁剑门剑冢秘境",   desc:"铁剑门历代长眠的剑冢，剑气纵横。", reqStage:1,  enemyLv:2,  rewards:["zisha_sword","purple_armor","wind_chase_boots"]},
  "spirit_beast":     {name:"灵兽山百兽谷秘境", desc:"灵兽山百兽谷，妖兽横行。", reqStage:1,  enemyLv:2,  rewards:["core_formation_pill","dragon_blood","spirit_gather_ring"]},
  "thunder_mountain": {name:"雷山雷霆秘境",    desc:"雷山派的雷霆秘境，雷光四射。", reqStage:1,  enemyLv:2,  rewards:["core_formation_pill","thunder_seal","wind_chase_boots"]},
  "ghost_spirit":     {name:"鬼灵门幽冥秘境",   desc:"鬼灵门幽冥秘境，阴气森森。", reqStage:2,  enemyLv:3,  rewards:["infant_formation_pill","ghost_face_shield","nether_flag","soul_flag"]},
  "blood_flame":      {name:"血焰教血池秘境",   desc:"血焰教血池秘境，血气冲天。", reqStage:2,  enemyLv:3,  rewards:["infant_formation_pill","poison_fang_dagger","blood_puppet_relic"]},
  "star_palace":      {name:"星宫星海秘境",     desc:"星宫的星海秘境，星光璀璨。", reqStage:3,  enemyLv:4,  rewards:["infant_formation_pill","star_moon_wheel","star_pendant","star_sand"]},
  "demon_valley":     {name:"魔道宗魔渊秘境",   desc:"魔道宗魔渊秘境，魔气滔天。", reqStage:3,  enemyLv:4,  rewards:["dragon_pattern_blade","nine_heaven_robe","spirit_devouring_bone"]},
  "spirit_world_sect":{name:"天宗天元秘境",     desc:"灵界天宗的天元秘境，灵气浓郁。", reqStage:4,  enemyLv:5,  rewards:["void_heaven_blade","nine_ghost_bone_armor","chaos_bell"]},
  "immortal_palace":  {name:"仙宫仙源秘境",     desc:"仙宫仙源秘境，仙气弥漫。", reqStage:8,  enemyLv:7,  rewards:["heaven_seal_seal","chaos_gourd","star_palace_mirror"]},
  "han_family":       {name:"韩家丹房秘境",     desc:"韩家祖传丹房秘境。", reqStage:0,  enemyLv:0,  rewards:["healing_pill","qi_pill","foundation_pill"]},
  "wang_family":      {name:"王家器冢秘境",     desc:"王家历代器冢秘境。", reqStage:0,  enemyLv:1,  rewards:["qingshuang_sword","blue_robe","wind_chase_boots"]},
  "mu_family":        {name:"慕容阵谷秘境",     desc:"慕容家阵法山谷秘境。", reqStage:1,  enemyLv:2,  rewards:["core_formation_pill","five_element_ring","zisha_sword"]},
  "li_family":        {name:"李家海府秘境",     desc:"李家海底府邸秘境。", reqStage:1,  enemyLv:2,  rewards:["core_formation_pill","star_sand","blue_silk_sword"]},
  "yun_family":       {name:"云家仙源秘境",     desc:"云家灵界仙源秘境。", reqStage:4,  enemyLv:5,  rewards:["void_heaven_blade","dragon_soul_bead","void_ring"]},
  "yao_family":       {name:"姚家丹源秘境",     desc:"姚家灵界丹源秘境。", reqStage:4,  enemyLv:5,  rewards:["immortal_longevity_pill","nine_turn_pill","heaven_longevity_fruit"]},
  "zhao_family":      {name:"赵家战谷秘境",     desc:"赵家慕兰战谷秘境。", reqStage:2,  enemyLv:3,  rewards:["infant_formation_pill","thunder_spear","ghost_face_shield"]},
  "qin_family":       {name:"秦家符冢秘境",     desc:"秦家祖传符冢秘境。", reqStage:0,  enemyLv:0,  rewards:["healing_pill","qi_pill","spirit_gather_ring"]},
};

// ===== 新增城镇特有副本 =====
const TOWN_DUNGEONS = {
  "长安城_古墓群":   {name:"长安古墓秘境",   desc:"长安城外古老的墓群，传说藏有上古修士遗宝。", reqStage:0,  enemyLv:1,  rewards:["foundation_pill","qingshuang_sword","blue_robe","spirit_gather_ring"],
    enemies:["stone_golem","iron_ape","poison_snake"], eventChance:0.35, expBonus:80,  stoneBonus:30},
  "长安城_落雁峰":   {name:"落雁峰秘境",     desc:"长安城外落雁峰，险峻异常，灵禽栖居。", reqStage:1,  enemyLv:2,  rewards:["core_formation_pill","zisha_sword","purple_armor","wind_chase_boots"],
    enemies:["blood_wolf","evil_cultivator","thousand_year_bat"], eventChance:0.35, expBonus:120, stoneBonus:40},
  "太南谷_百毒谷":   {name:"百毒谷秘境",     desc:"太南谷外百毒谷，毒虫遍地，却盛产灵药。", reqStage:0,  enemyLv:1,  rewards:["healing_pill","spirit_grass","foundation_pill","qingshuang_sword"],
    enemies:["poison_snake","wild_beast_lq","iron_ape"], eventChance:0.35, expBonus:60,  stoneBonus:20},
  "太南谷_幽冥涧":   {name:"幽冥涧秘境",     desc:"太南谷外幽冥涧，阴气森森，鬼修出没。", reqStage:1,  enemyLv:2,  rewards:["core_formation_pill","blue_silk_sword","five_element_ring"],
    enemies:["evil_cultivator","bandit","wild_beast_lq"], eventChance:0.35, expBonus:100, stoneBonus:35},
  "太南谷_清风剑阁": {name:"清风剑阁秘境",   desc:"太南谷清风剑阁遗址，剑气残留。", reqStage:0,  enemyLv:0,  rewards:["iron_sword","qi_pill","healing_pill","spirit_grass"],
    enemies:["wild_beast_lq","iron_ape","poison_snake"], eventChance:0.3,  expBonus:50,  stoneBonus:15},
  "长安城_青云观":   {name:"青云观秘境",     desc:"长安城青云观后山秘境，道法自然。", reqStage:0,  enemyLv:0,  rewards:["qi_pill","healing_pill","spirit_gather_ring","blue_robe"],
    enemies:["wild_beast_lq","iron_ape","stone_golem"], eventChance:0.3,  expBonus:60,  stoneBonus:20},
  "天南坊市城_荒野小径": {name:"荒野小径秘境", desc:"天南坊市城外荒野小径，盗匪出没。", reqStage:0, enemyLv:0, rewards:["healing_pill","iron_sword","spirit_grass","cloth_robe"],
    enemies:["bandit","blood_wolf","wild_beast_lq"], eventChance:0.35, expBonus:50, stoneBonus:20},
  "天南坊市城_古修士洞府": {name:"古修士洞府秘境", desc:"天南坊市城外古修士洞府，机缘与危险并存。", reqStage:1, enemyLv:1, rewards:["foundation_pill","qingshuang_sword","blue_robe","spirit_gather_ring"],
    enemies:["evil_cultivator","blood_wolf","thousand_year_bat"], eventChance:0.35, expBonus:100, stoneBonus:40},
  "天南坊市城_灵石矿脉": {name:"灵石矿脉秘境", desc:"天南坊市城外灵石矿脉，灵石丰富但有妖兽守护。", reqStage:0, enemyLv:0, rewards:["spirit_stone","spirit_grass","healing_pill","iron_sword"],
    enemies:["wild_beast_lq","iron_ape","poison_snake"], eventChance:0.3, expBonus:40, stoneBonus:50},
  "天南坊市城_毒蛇谷": {name:"毒蛇谷秘境",   desc:"天南坊市城外毒蛇谷，毒蛇遍地却盛产灵药。", reqStage:1, enemyLv:1, rewards:["foundation_pill","spirit_grass","blue_robe","healing_pill"],
    enemies:["poison_snake","wild_beast_lq","blood_wolf"], eventChance:0.35, expBonus:80, stoneBonus:25},
};

// ===== 新增剧情NPC（异性，基于小说） =====
const NEW_STORY_NPCS = {
  "nan_gong_wan": {
    name:"南宫婉", desc:"黄枫谷天才女修，性情清冷",
    isFemale:true, cultStage:1,
    locations: [
      {minCult:0, area:"黄枫谷", subArea:"黄枫谷主殿", desc:"在黄枫谷修炼"},
      {minCult:1, area:"天南坊市城", subArea:"丹药铺", desc:"在天南坊市城采买丹药"},
      {minCult:2, area:"天南坊市城", subArea:"灵石矿脉", desc:"在坊市城外荒野历练"},
      {minCult:4, area:"乱星海", subArea:"星宫", desc:"在乱星海历练"},
      {minCult:6, area:"虚天殿", subArea:"虚天殿内殿", desc:"在虚天殿探索"},
    ],
    dialogues: {
      冷淡:"「你是何人？休要打扰本姑娘清修。」",
      客气:"「道友也是来历练的？多多保重。」",
      友善:"「你的修为精进不少，看来天赋不凡。」",
      亲密:"「我等你很久了……你可知道我的心意？」",
    },
  },
  "dong_xuan": {
    name:"董萱儿", desc:"天南坊市城女修，性格活泼",
    isFemale:true, cultStage:0,
    locations: [
      {minCult:0, area:"天南坊市城", subArea:"茶馆", desc:"在茶馆闲聊"},
      {minCult:1, area:"天南坊市城", subArea:"拍卖行", desc:"在拍卖行看热闹"},
      {minCult:2, area:"乱星海渡口", subArea:"海鲜酒楼", desc:"在酒楼吃饭"},
      {minCult:4, area:"乱星海", subArea:"星砂矿岛", desc:"在星砂矿岛冒险"},
      {minCult:6, area:"虚天殿", subArea:"虚天殿外围", desc:"在虚天殿外围修炼"},
    ],
    dialogues: {
      冷淡:"「又来一个搭讪的，走开走开！」",
      客气:"「道友好啊，最近有什么新鲜事吗？」",
      友善:"「哈哈，每次见到你都很有趣！」",
      亲密:"「你要一直陪着我哦……」",
    },
  },
  "yao_xi": {
    name:"瑶姬", desc:"鬼灵门叛逃女修，身世神秘",
    isFemale:true, cultStage:2,
    locations: [
      {minCult:2, area:"天南坊市城", subArea:"毒蛇谷", desc:"在毒蛇谷出没"},
      {minCult:3, area:"虚天殿", subArea:"虚天秘境", desc:"在虚天秘境探索"},
      {minCult:5, area:"慕兰草原", subArea:"战场营地", desc:"在战场营地疗伤"},
      {minCult:7, area:"坠魔谷", subArea:"古魔封印地", desc:"在古魔封印地附近"},
    ],
    dialogues: {
      冷淡:"「……别靠近我。」",
      客气:"「你身上没有魔气，看来不是追杀我的人。」",
      友善:"「谢谢你没有追问我的过去。」",
      亲密:"「你是第一个让我感到安心的人……」",
    },
  },
  "mu_yuan_ying": {
    name:"慕元婴", desc:"慕兰草原女修士，豪爽直率",
    isFemale:true, cultStage:3,
    locations: [
      {minCult:3, area:"慕兰草原", subArea:"草原集市", desc:"在草原集市买卖"},
      {minCult:4, area:"慕兰草原", subArea:"战场营地", desc:"在战场营地驻扎"},
      {minCult:6, area:"坠魔谷", subArea:"坠魔谷入口", desc:"在坠魔谷入口探险"},
      {minCult:8, area:"灵界入口", subArea:"飞升台", desc:"在飞升台附近"},
    ],
    dialogues: {
      冷淡:"「你是谁？少在这里碍眼。」",
      客气:"「道友也是来战场历练的？有胆量。」",
      友善:"「走，我请你喝酒！战场上就得豪爽！」",
      亲密:"「等这场仗打完，我就跟你走。」",
    },
  },
  "su_qing": {
    name:"苏青", desc:"灵界散修女修，冷淡寡言",
    isFemale:true, cultStage:4,
    locations: [
      {minCult:4, area:"灵界", subArea:"灵界荒原", desc:"在灵界荒原独行"},
      {minCult:5, area:"灵界", subArea:"灵界仙城", desc:"在灵界仙城修炼"},
      {minCult:7, area:"灵界", subArea:"万灵秘境", desc:"在万灵秘境探索"},
    ],
    dialogues: {
      冷淡:"「……」她只是冷冷看了你一眼。",
      客气:"「灵界凶险，道友小心行事。」",
      友善:"「你的实力不错，我们可以同行。」",
      亲密:"「难得遇到让我信任的人……」",
    },
  },
  "yin_yue": {
    name:"银月", desc:"妖族少女化形，天真烂漫",
    isFemale:true, cultStage:2,
    locations: [
      {minCult:2, area:"天南坊市城", subArea:"灵石矿脉", desc:"在灵石矿脉附近玩耍"},
      {minCult:3, area:"乱星海", subArea:"星砂矿岛", desc:"在星砂矿岛看星星"},
      {minCult:5, area:"虚天殿", subArea:"虚天秘境", desc:"在虚天秘境出没"},
      {minCult:7, area:"坠魔谷", subArea:"坠魔谷深处", desc:"在坠魔谷深处修炼"},
    ],
    dialogues: {
      冷淡:"「你是坏人吗？我走开！」",
      客气:"「你好呀！你身上有好闻的灵气。」",
      友善:"「嘿嘿，你这个人不错嘛！下次带我一起冒险好不好？」",
      亲密:"「银月最喜欢你了！你要一直陪着银月哦！」",
    },
  },
};

// ===== 支线任务定义（10条以上） =====
const SIDE_QUESTS = {
  "sq_lost_disciple": {
    id:"sq_lost_disciple", name:"失踪的弟子", type:"side",
    triggerNPC:"generic", triggerDesc:"在城镇遇到焦急的修士",
    desc:"一位修士的师弟在野外失踪，请帮忙寻找。",
    target:"在野外探索时找到失踪弟子",
    minCult:0,
    reward:{stones:300, exp:500, item:"foundation_pill"},
    checkFn:"checkLostDisciple",
  },
  "sq_stolen_treasure": {
    id:"sq_stolen_treasure", name:"失窃的宝物", type:"side",
    triggerNPC:"generic", triggerDesc:"遇到被盗宝的修士",
    desc:"一位修士的宝物被贼人偷走，请帮忙追回。",
    target:"击败盗贼夺回宝物",
    minCult:1,
    reward:{stones:500, exp:800, item:"zisha_sword"},
    checkFn:"checkStolenTreasure",
  },
  "sq_alchemy_request": {
    id:"sq_alchemy_request", name:"炼丹委托", type:"side",
    triggerNPC:"generic", triggerDesc:"遇到需要丹药的修士",
    desc:"一位修士需要特殊丹药，请帮忙炼制或寻找材料。",
    target:"交付3株灵草给委托人",
    minCult:0,
    reward:{stones:200, exp:400, item:"healing_pill"},
    checkFn:"checkAlchemyRequest",
  },
  "sq_beast_subdue": {
    id:"sq_beast_subdue", name:"妖兽为患", type:"side",
    triggerNPC:"generic", triggerDesc:"遇到求助的村民",
    desc:"附近妖兽为患，请帮忙清除。",
    target:"击败3只野外妖兽",
    minCult:1,
    reward:{stones:400, exp:600, item:"blue_robe"},
    checkFn:"checkBeastSubdue",
  },
  "sq_escort_merchant": {
    id:"sq_escort_merchant", name:"护送商队", type:"side",
    triggerNPC:"generic", triggerDesc:"遇到需要护送的商队",
    desc:"一支商队需要护送通过危险区域。",
    target:"护送商队安全到达目的地",
    minCult:1,
    reward:{stones:600, exp:1000, item:"spirit_gather_ring"},
    checkFn:"checkEscortMerchant",
  },
  "sq_rival_duel": {
    id:"sq_rival_duel", name:"宿敌决斗", type:"side",
    triggerNPC:"generic", triggerDesc:"遇到被宿敌挑战的修士",
    desc:"一位修士被宿敌挑战，请帮忙助拳。",
    target:"击败挑战者",
    minCult:2,
    reward:{stones:800, exp:1500, item:"core_formation_pill"},
    checkFn:"checkRivalDuel",
  },
  "sq_ancient_map": {
    id:"sq_ancient_map", name:"古地图之谜", type:"side",
    triggerNPC:"generic", triggerDesc:"遇到持有古地图的修士",
    desc:"一张古地图指向某处宝藏，请帮忙探索。",
    target:"探索洞天福地找到宝藏",
    minCult:2,
    reward:{stones:1000, exp:2000, item:"wind_chase_boots"},
    checkFn:"checkAncientMap",
  },
  "sq_missing_alchemist": {
    id:"sq_missing_alchemist", name:"失踪的炼丹师", type:"side",
    triggerNPC:"generic", triggerDesc:"遇到寻找师父的弟子",
    desc:"一位炼丹师在洞天中失踪，请帮忙寻找。",
    target:"在洞天福地中找到炼丹师",
    minCult:3,
    reward:{stones:1500, exp:3000, item:"infant_formation_pill"},
    checkFn:"checkMissingAlchemist",
  },
  "sq_demon_removal": {
    id:"sq_demon_removal", name:"驱魔除妖", type:"side",
    triggerNPC:"generic", triggerDesc:"遇到被魔气困扰的修士",
    desc:"一处秘境被魔气侵蚀，请帮忙清除。",
    target:"击败秘境中的魔物",
    minCult:3,
    reward:{stones:2000, exp:4000, item:"dragon_scale_armor"},
    checkFn:"checkDemonRemoval",
  },
  "sq_spirit_vein_dispute": {
    id:"sq_spirit_vein_dispute", name:"灵脉之争", type:"side",
    triggerNPC:"generic", triggerDesc:"遇到争夺灵脉的修士",
    desc:"两方修士争夺一条灵脉，请帮忙调解或夺取。",
    target:"夺取灵脉控制权",
    minCult:2,
    reward:{stones:1200, exp:2500, item:"five_element_ring"},
    checkFn:"checkSpiritVeinDispute",
  },
  "sq_cursed_blade": {
    id:"sq_cursed_blade", name:"诅咒之刃", type:"side",
    triggerNPC:"generic", triggerDesc:"遇到被诅咒武器困扰的修士",
    desc:"一把被诅咒的法器需要特殊材料解除诅咒。",
    target:"收集2份蛟龙血",
    minCult:2,
    reward:{stones:1500, exp:3000, item:"blue_silk_sword"},
    checkFn:"checkCursedBlade",
  },
  "sq_heavenly_herb": {
    id:"sq_heavenly_herb", name:"天材地宝", type:"side",
    triggerNPC:"generic", triggerDesc:"遇到寻找天材地宝的修士",
    desc:"一种天材地宝在危险之地生长，请帮忙采集。",
    target:"采集到天材地宝",
    minCult:4,
    reward:{stones:3000, exp:6000, item:"nine_heaven_robe"},
    checkFn:"checkHeavenlyHerb",
  },
};

// ===== 新增副本/洞天类型 =====
const NEW_DUNGEON_TYPES = [
  {
    name:"上古剑冢", desc:"一片荒芜的剑冢，无数断裂的飞剑插在地面，剑气纵横，令人心惊。",
    expBonus:1500, stoneBonus:500, itemChance:0.7,
    enemyChance:0.7, enemyTypes:["sword_spirit","sword_puppet","sword_beast"],
    itemPool:["blue_silk_sword","wind_lei_sword","zisha_sword","thunder_spear","ice_soul_sword"],
  },
  {
    name:"龙脉秘境", desc:"地底深处传来龙吟之声，这里似乎是一条龙脉所在之处。",
    expBonus:2000, stoneBonus:1000, itemChance:0.6,
    enemyChance:0.8, enemyTypes:["dragon_spawn","earth_dragon","dragon_guardian"],
    itemPool:["dragon_blood","dragon_scale_armor","dragon_soul_bead","nine_dragon_whip"],
  },
  {
    name:"幻境迷阵", desc:"四周景象不断变化，分不清虚实，这是一处强大的幻境迷阵。",
    expBonus:1800, stoneBonus:300, itemChance:0.5,
    enemyChance:0.6, enemyTypes:["illusion_spirit","mirror_demon","phantom_beast"],
    itemPool:["spirit_conceal_pendant","blood_jade_bracelet","star_pendant","void_ring"],
  },
  {
    name:"冰火两仪洞", desc:"洞内一半冰天雪地，一半烈焰滔天，冰火两仪之力在此交汇。",
    expBonus:2500, stoneBonus:800, itemChance:0.7,
    enemyChance:0.8, enemyTypes:["ice_fire_beast","element_guardian","yin_yang_spirit"],
    itemPool:["ice_soul_sword","phoenix_feather_cloak","flame_whip","frost_blade"],
  },
  {
    name:"时空遗迹", desc:"空间在此扭曲，时间流逝异常，这是一处远古时空遗迹。",
    expBonus:3000, stoneBonus:1500, itemChance:0.8,
    enemyChance:0.7, enemyTypes:["time_spirit","space_beast","void_guardian"],
    itemPool:["void_ring","space_ring","chaos_bell","chaos_gourd","spirit_devouring_bone"],
  },
];

// ===== 新增副本敌人 =====
const NEW_DUNGEON_ENEMIES = {
  "sword_spirit":{name:"剑灵",hp:4000,atk:250,def:100,exp:2500,stone:300,drop:"blue_silk_sword",dropRate:0.3},
  "sword_puppet":{name:"剑傀儡",hp:6000,atk:200,def:200,exp:3000,stone:400,drop:"wind_lei_sword",dropRate:0.3},
  "sword_beast":{name:"剑齿兽",hp:5000,atk:280,def:150,exp:2800,stone:350,drop:"ice_soul_sword",dropRate:0.25},
  "dragon_spawn":{name:"龙裔",hp:8000,atk:350,def:250,exp:4000,stone:600,drop:"dragon_blood",dropRate:0.4},
  "earth_dragon":{name:"地龙",hp:12000,atk:400,def:350,exp:6000,stone:1000,drop:"dragon_scale_armor",dropRate:0.3},
  "dragon_guardian":{name:"龙脉守护者",hp:15000,atk:500,def:400,exp:8000,stone:1500,drop:"dragon_soul_bead",dropRate:0.2},
  "illusion_spirit":{name:"幻灵",hp:3000,atk:300,def:80,exp:2500,stone:300,drop:"spirit_conceal_pendant",dropRate:0.3},
  "mirror_demon":{name:"镜魔",hp:5000,atk:350,def:200,exp:3500,stone:500,drop:"blood_jade_bracelet",dropRate:0.25},
  "phantom_beast":{name:"幻兽",hp:6000,atk:320,def:180,exp:3200,stone:450,drop:"star_pendant",dropRate:0.2},
  "ice_fire_beast":{name:"冰火兽",hp:10000,atk:450,def:300,exp:5500,stone:800,drop:"ice_soul_sword",dropRate:0.3},
  "element_guardian":{name:"两仪守护者",hp:12000,atk:500,def:350,exp:6500,stone:1200,drop:"phoenix_feather_cloak",dropRate:0.25},
  "yin_yang_spirit":{name:"阴阳灵",hp:8000,atk:400,def:250,exp:5000,stone:700,drop:"frost_blade",dropRate:0.3},
  "time_spirit":{name:"时灵",hp:15000,atk:550,def:400,exp:8000,stone:2000,drop:"void_ring",dropRate:0.2},
  "space_beast":{name:"虚空兽",hp:18000,atk:600,def:450,exp:9000,stone:2500,drop:"space_ring",dropRate:0.2},
  "void_guardian":{name:"时空守护者",hp:25000,atk:700,def:500,exp:15000,stone:4000,drop:"chaos_bell",dropRate:0.15},
};

// 合并新敌人到全局
Object.assign(CAVE_STRONG_ENEMIES, NEW_DUNGEON_ENEMIES);
